### ISSUE TITLE
Validation request

### ISSUE THREAD

**Issue by Klbrtmr** [CsharptutorialHungary/egyetemikurzus-2023-tavasz#1]
@webmaster442 @Ethax @GaborTanbaEvo 
Hello, ahogy óra után említettem légyszi rá tudnátok nézni, hogy valid-e így a generikus lista felhasználása illetve a record class alkalmazása. 
Generikus lista: Program.cs  28-38. sor, 887-959. sor között

Mivel a feladatleírás nem tért ki részletekre, hogy milyen módon kéne alkalmazni őket, így ezért helyesnek gondolnám.

Köszi!

**Comment by webmaster442** [comment]
Hello

Jó lesz, de pár észrevétel:

- A `MyConsoleColor` osztályod field-et publikál ki. Ez legyen már inkább property.
- Ugyan ebben az osztályban `adding` metódus: Egyrészt naming violation, másrészről pedig a listának van egy AddRange metódusa, amivel meg lehetne az egészet spórolni.
- Az, hogy a Program.cs 961 sor nem igen jó. Jó lenne kisebb részekre szétszedni
- A `convertToInt` metódusban lehetne használni a TryParse metódusát az int-nek egyszerűsítésként.
-  A 398-as sortól nem ártana több metódusra szét szedni, mert ez így nagyon nem SOLID.
